#!/usr/bin/env bash
# script to permanently redirect
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
fill="location /redirect_me {\nrewrite ^/(.*)$ https://youtu.be/vlkrUC-xJak permanent;\n}\n"
sudo sed -i "/# Only/ i $fill" /etc/nginx/sites-available/default
sudo service nginx restart
